language: minimal
services:
  - docker
env:
  global:
    - REPO_NAME=cseelye
    - IMAGE_NAME=tool-dev
    - IMAGE_TAG=latest
dist: bionic
jobs:
  include:
    - stage: "build and test container"
      env:
        DOCKERFILE_NAME=Dockerfile
      before_script: docker pull $REPO_NAME/$IMAGE_NAME:$IMAGE_TAG || true
      script:
        - docker image build
              --cache-from $REPO_NAME/$IMAGE_NAME:$IMAGE_TAG
              --tag $REPO_NAME/$IMAGE_NAME:$IMAGE_TAG
              --file $DOCKERFILE_NAME
              .
        - docker container run --rm 
              --volume $(pwd):/work 
              --workdir /work 
              $REPO_NAME/$IMAGE_NAME:$IMAGE_TAG
              make test
